X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16)
Received: (qmail 21680 invoked from network); 12 May 2014 17:05:13 -0000
From: root@example.com (Cron Daemon)
To: root@example.com
Subject: Cron <root@example.com> /root/bin/cron/script.sh
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
Date: Mon, 12 May 2014 19:04:42 +0200
Message-Id: <1399914282.010803.25751.nullmailer@example.de>

fatal error: autodiscovery failed
